#!/usr/bin/env bash
set -euo pipefail
echo "Validating updated repo paths (new_path)..."
if [ -e "/Volumes/psiqo/autonoms_final_secure_pack/autonoma-x" ]; then echo "[OK] /Volumes/psiqo/autonoms_final_secure_pack/autonoma-x"; else echo "[MISSING] /Volumes/psiqo/autonoms_final_secure_pack/autonoma-x"; fi
if [ -e "/Volumes/psiqo/autonomax-hub" ]; then echo "[OK] /Volumes/psiqo/autonomax-hub"; else echo "[MISSING] /Volumes/psiqo/autonomax-hub"; fi
if [ -e "/Volumes/psiqo/youtube_ai_app_v2.5/fiverr_business/fiverr_business" ]; then echo "[OK] /Volumes/psiqo/youtube_ai_app_v2.5/fiverr_business/fiverr_business"; else echo "[MISSING] /Volumes/psiqo/youtube_ai_app_v2.5/fiverr_business/fiverr_business"; fi
if [ -e "/Volumes/psiqo/_lazy/business_opportunity_platform/business-dashboard" ]; then echo "[OK] /Volumes/psiqo/_lazy/business_opportunity_platform/business-dashboard"; else echo "[MISSING] /Volumes/psiqo/_lazy/business_opportunity_platform/business-dashboard"; fi
if [ -e "/Volumes/psiqo/_lazy/business-dashboard" ]; then echo "[OK] /Volumes/psiqo/_lazy/business-dashboard"; else echo "[MISSING] /Volumes/psiqo/_lazy/business-dashboard"; fi
if [ -e "/Volumes/psiqo/AutonomaX_AI_Integration_Starter_v11_full" ]; then echo "[OK] /Volumes/psiqo/AutonomaX_AI_Integration_Starter_v11_full"; else echo "[MISSING] /Volumes/psiqo/AutonomaX_AI_Integration_Starter_v11_full"; fi
if [ -e "/Volumes/psiqo/AutonomaX_API_Commander" ]; then echo "[OK] /Volumes/psiqo/AutonomaX_API_Commander"; else echo "[MISSING] /Volumes/psiqo/AutonomaX_API_Commander"; fi
if [ -e "/Volumes/psiqo/AutonomaX_Studio" ]; then echo "[OK] /Volumes/psiqo/AutonomaX_Studio"; else echo "[MISSING] /Volumes/psiqo/AutonomaX_Studio"; fi
if [ -e "/Volumes/psiqo/autonomax-hub/AutonomaX-Studio" ]; then echo "[OK] /Volumes/psiqo/autonomax-hub/AutonomaX-Studio"; else echo "[MISSING] /Volumes/psiqo/autonomax-hub/AutonomaX-Studio"; fi
if [ -e "/Volumes/psiqo/autonoms_final_secure_pack" ]; then echo "[OK] /Volumes/psiqo/autonoms_final_secure_pack"; else echo "[MISSING] /Volumes/psiqo/autonoms_final_secure_pack"; fi
if [ -e "/Volumes/psiqo/Commander_Orchestrated_Online" ]; then echo "[OK] /Volumes/psiqo/Commander_Orchestrated_Online"; else echo "[MISSING] /Volumes/psiqo/Commander_Orchestrated_Online"; fi
if [ -e "/Volumes/psiqo/youtube_ai_app_v2.5/revenue-accelerator/etsy_commander" ]; then echo "[OK] /Volumes/psiqo/youtube_ai_app_v2.5/revenue-accelerator/etsy_commander"; else echo "[MISSING] /Volumes/psiqo/youtube_ai_app_v2.5/revenue-accelerator/etsy_commander"; fi
if [ -e "/Volumes/psiqo/youtube_ai_app_v2.5/revenue-accelerator/etsy_commander_backup" ]; then echo "[OK] /Volumes/psiqo/youtube_ai_app_v2.5/revenue-accelerator/etsy_commander_backup"; else echo "[MISSING] /Volumes/psiqo/youtube_ai_app_v2.5/revenue-accelerator/etsy_commander_backup"; fi
if [ -e "/Volumes/psiqo/propulse-app" ]; then echo "[OK] /Volumes/psiqo/propulse-app"; else echo "[MISSING] /Volumes/psiqo/propulse-app"; fi
if [ -e "/Volumes/psiqo/__ProPulse_Group__" ]; then echo "[OK] /Volumes/psiqo/__ProPulse_Group__"; else echo "[MISSING] /Volumes/psiqo/__ProPulse_Group__"; fi
if [ -e "/Volumes/psiqo/__ProPulse_Group__/propulse-autonomax" ]; then echo "[OK] /Volumes/psiqo/__ProPulse_Group__/propulse-autonomax"; else echo "[MISSING] /Volumes/psiqo/__ProPulse_Group__/propulse-autonomax"; fi
if [ -e "/Volumes/psiqo/__ProPulse_Group__/propulse-autonomax-github/propulse-autonomax" ]; then echo "[OK] /Volumes/psiqo/__ProPulse_Group__/propulse-autonomax-github/propulse-autonomax"; else echo "[MISSING] /Volumes/psiqo/__ProPulse_Group__/propulse-autonomax-github/propulse-autonomax"; fi
if [ -e "/Volumes/psiqo/__ProPulse_Group__/propulse-autonomax/propulse-autonomax" ]; then echo "[OK] /Volumes/psiqo/__ProPulse_Group__/propulse-autonomax/propulse-autonomax"; else echo "[MISSING] /Volumes/psiqo/__ProPulse_Group__/propulse-autonomax/propulse-autonomax"; fi
if [ -e "/Volumes/psiqo/__ProPulse_Group__/ProPulseApp_Final_Base" ]; then echo "[OK] /Volumes/psiqo/__ProPulse_Group__/ProPulseApp_Final_Base"; else echo "[MISSING] /Volumes/psiqo/__ProPulse_Group__/ProPulseApp_Final_Base"; fi
if [ -e "/Volumes/psiqo/__ProPulse_Group__/ProPulseApp_Final_Base copy 2" ]; then echo "[OK] /Volumes/psiqo/__ProPulse_Group__/ProPulseApp_Final_Base copy 2"; else echo "[MISSING] /Volumes/psiqo/__ProPulse_Group__/ProPulseApp_Final_Base copy 2"; fi
if [ -e "/Volumes/psiqo/__ProPulse_Group__/ProPulseApp_Final_Base copy 2/app" ]; then echo "[OK] /Volumes/psiqo/__ProPulse_Group__/ProPulseApp_Final_Base copy 2/app"; else echo "[MISSING] /Volumes/psiqo/__ProPulse_Group__/ProPulseApp_Final_Base copy 2/app"; fi
if [ -e "/Volumes/psiqo/__ProPulse_Group__/ProPulseApp_Final_Base copy 2/app/services/propulse-autonomax_old" ]; then echo "[OK] /Volumes/psiqo/__ProPulse_Group__/ProPulseApp_Final_Base copy 2/app/services/propulse-autonomax_old"; else echo "[MISSING] /Volumes/psiqo/__ProPulse_Group__/ProPulseApp_Final_Base copy 2/app/services/propulse-autonomax_old"; fi
if [ -e "/Volumes/psiqo/__ProPulse_Group__/ProPulseApp_Final_Base copy 2/scripts" ]; then echo "[OK] /Volumes/psiqo/__ProPulse_Group__/ProPulseApp_Final_Base copy 2/scripts"; else echo "[MISSING] /Volumes/psiqo/__ProPulse_Group__/ProPulseApp_Final_Base copy 2/scripts"; fi
if [ -e "/Volumes/psiqo/__ProPulse_Group__/ProPulseApp_Final_Base/app" ]; then echo "[OK] /Volumes/psiqo/__ProPulse_Group__/ProPulseApp_Final_Base/app"; else echo "[MISSING] /Volumes/psiqo/__ProPulse_Group__/ProPulseApp_Final_Base/app"; fi
if [ -e "/Volumes/psiqo/__ProPulse_Group__/ProPulseApp_Final_Base/app/services/propulse-autonomax_old" ]; then echo "[OK] /Volumes/psiqo/__ProPulse_Group__/ProPulseApp_Final_Base/app/services/propulse-autonomax_old"; else echo "[MISSING] /Volumes/psiqo/__ProPulse_Group__/ProPulseApp_Final_Base/app/services/propulse-autonomax_old"; fi
if [ -e "/Volumes/psiqo/__ProPulse_Group__/ProPulseApp_Final_Base/scripts" ]; then echo "[OK] /Volumes/psiqo/__ProPulse_Group__/ProPulseApp_Final_Base/scripts"; else echo "[MISSING] /Volumes/psiqo/__ProPulse_Group__/ProPulseApp_Final_Base/scripts"; fi
if [ -e "/Volumes/psiqo/__ProPulse_Group__/ProPulseApp_Stable_Deployment" ]; then echo "[OK] /Volumes/psiqo/__ProPulse_Group__/ProPulseApp_Stable_Deployment"; else echo "[MISSING] /Volumes/psiqo/__ProPulse_Group__/ProPulseApp_Stable_Deployment"; fi
if [ -e "/Volumes/psiqo/__ProPulse_Group__/ProPulseApp_Stable_Deployment/app/services/propulse-autonomax" ]; then echo "[OK] /Volumes/psiqo/__ProPulse_Group__/ProPulseApp_Stable_Deployment/app/services/propulse-autonomax"; else echo "[MISSING] /Volumes/psiqo/__ProPulse_Group__/ProPulseApp_Stable_Deployment/app/services/propulse-autonomax"; fi
if [ -e "/Volumes/psiqo/youtube_ai_app_v2.5" ]; then echo "[OK] /Volumes/psiqo/youtube_ai_app_v2.5"; else echo "[MISSING] /Volumes/psiqo/youtube_ai_app_v2.5"; fi
if [ -e "/Volumes/psiqo/youtube_ai_app_v2.5/youtube-ai-platform" ]; then echo "[OK] /Volumes/psiqo/youtube_ai_app_v2.5/youtube-ai-platform"; else echo "[MISSING] /Volumes/psiqo/youtube_ai_app_v2.5/youtube-ai-platform"; fi
if [ -e "/Volumes/psiqo/youtube-ai-platform" ]; then echo "[OK] /Volumes/psiqo/youtube-ai-platform"; else echo "[MISSING] /Volumes/psiqo/youtube-ai-platform"; fi
if [ -e "/Volumes/psiqo/youtube_ai_app_clean" ]; then echo "[OK] /Volumes/psiqo/youtube_ai_app_clean"; else echo "[MISSING] /Volumes/psiqo/youtube_ai_app_clean"; fi
if [ -e "/Volumes/psiqo/youtube_ai_platform_backup_edit" ]; then echo "[OK] /Volumes/psiqo/youtube_ai_platform_backup_edit"; else echo "[MISSING] /Volumes/psiqo/youtube_ai_platform_backup_edit"; fi
if [ -e "/Volumes/psiqo/_salvage/20250810_worx/mega_all_pack" ]; then echo "[OK] /Volumes/psiqo/_salvage/20250810_worx/mega_all_pack"; else echo "[MISSING] /Volumes/psiqo/_salvage/20250810_worx/mega_all_pack"; fi
if [ -e "/Volumes/psiqo/youtube_ai_app_clean copy 4" ]; then echo "[OK] /Volumes/psiqo/youtube_ai_app_clean copy 4"; else echo "[MISSING] /Volumes/psiqo/youtube_ai_app_clean copy 4"; fi
if [ -e "/Volumes/psiqo/youtube_ai_app_clean copy 5" ]; then echo "[OK] /Volumes/psiqo/youtube_ai_app_clean copy 5"; else echo "[MISSING] /Volumes/psiqo/youtube_ai_app_clean copy 5"; fi
if [ -e "/Volumes/psiqo/__bop" ]; then echo "[OK] /Volumes/psiqo/__bop"; else echo "[MISSING] /Volumes/psiqo/__bop"; fi
if [ -e "/Volumes/psiqo/__bop_v01" ]; then echo "[OK] /Volumes/psiqo/__bop_v01"; else echo "[MISSING] /Volumes/psiqo/__bop_v01"; fi
if [ -e "/Volumes/psiqo/__bop_v01/__MACOSX" ]; then echo "[OK] /Volumes/psiqo/__bop_v01/__MACOSX"; else echo "[MISSING] /Volumes/psiqo/__bop_v01/__MACOSX"; fi
if [ -e "/Volumes/psiqo/__bop/__MACOSX" ]; then echo "[OK] /Volumes/psiqo/__bop/__MACOSX"; else echo "[MISSING] /Volumes/psiqo/__bop/__MACOSX"; fi
if [ -e "/Volumes/psiqo/bop_final_repo copy/bop/__MACOSX" ]; then echo "[OK] /Volumes/psiqo/bop_final_repo copy/bop/__MACOSX"; else echo "[MISSING] /Volumes/psiqo/bop_final_repo copy/bop/__MACOSX"; fi
if [ -e "/Volumes/psiqo/bop_final_repo/bop_merged_platform/__MACOSX" ]; then echo "[OK] /Volumes/psiqo/bop_final_repo/bop_merged_platform/__MACOSX"; else echo "[MISSING] /Volumes/psiqo/bop_final_repo/bop_merged_platform/__MACOSX"; fi
if [ -e "/Volumes/psiqo/gpt-engineer" ]; then echo "[OK] /Volumes/psiqo/gpt-engineer"; else echo "[MISSING] /Volumes/psiqo/gpt-engineer"; fi
if [ -e "/Volumes/psiqo/bop_final_repo copy/bop" ]; then echo "[OK] /Volumes/psiqo/bop_final_repo copy/bop"; else echo "[MISSING] /Volumes/psiqo/bop_final_repo copy/bop"; fi
if [ -e "/Volumes/psiqo/bop_final_repo/bop_merged_platform" ]; then echo "[OK] /Volumes/psiqo/bop_final_repo/bop_merged_platform"; else echo "[MISSING] /Volumes/psiqo/bop_final_repo/bop_merged_platform"; fi
if [ -e "/Volumes/psiqo/_project_/IWS/b4-code/_RichieRiched/RR-04/builder-app" ]; then echo "[OK] /Volumes/psiqo/_project_/IWS/b4-code/_RichieRiched/RR-04/builder-app"; else echo "[MISSING] /Volumes/psiqo/_project_/IWS/b4-code/_RichieRiched/RR-04/builder-app"; fi
if [ -e "/Volumes/psiqo/__bopper/business-dashboard" ]; then echo "[OK] /Volumes/psiqo/__bopper/business-dashboard"; else echo "[MISSING] /Volumes/psiqo/__bopper/business-dashboard"; fi
if [ -e "/Volumes/psiqo/ACE_Framework" ]; then echo "[OK] /Volumes/psiqo/ACE_Framework"; else echo "[MISSING] /Volumes/psiqo/ACE_Framework"; fi
if [ -e "/Volumes/psiqo/ACE_Framework_0" ]; then echo "[OK] /Volumes/psiqo/ACE_Framework_0"; else echo "[MISSING] /Volumes/psiqo/ACE_Framework_0"; fi
if [ -e "/Volumes/psiqo/OpenAI_Agent_Swarm" ]; then echo "[OK] /Volumes/psiqo/OpenAI_Agent_Swarm"; else echo "[MISSING] /Volumes/psiqo/OpenAI_Agent_Swarm"; fi
if [ -e "/Volumes/psiqo/_project_/__copilot/ecommerce_project" ]; then echo "[OK] /Volumes/psiqo/_project_/__copilot/ecommerce_project"; else echo "[MISSING] /Volumes/psiqo/_project_/__copilot/ecommerce_project"; fi
if [ -e "/Volumes/psiqo/_project_/ecommerce_project" ]; then echo "[OK] /Volumes/psiqo/_project_/ecommerce_project"; else echo "[MISSING] /Volumes/psiqo/_project_/ecommerce_project"; fi
if [ -e "/Volumes/psiqo/_project_/app_v01_aida-actionsgpt/gpte" ]; then echo "[OK] /Volumes/psiqo/_project_/app_v01_aida-actionsgpt/gpte"; else echo "[MISSING] /Volumes/psiqo/_project_/app_v01_aida-actionsgpt/gpte"; fi
if [ -e "/Volumes/psiqo/gpt-eng/gpt-engineer/projects/__gpte/gpte" ]; then echo "[OK] /Volumes/psiqo/gpt-eng/gpt-engineer/projects/__gpte/gpte"; else echo "[MISSING] /Volumes/psiqo/gpt-eng/gpt-engineer/projects/__gpte/gpte"; fi
if [ -e "/Volumes/psiqo/_project_/IWS/b4-code/gpte_rr03" ]; then echo "[OK] /Volumes/psiqo/_project_/IWS/b4-code/gpte_rr03"; else echo "[MISSING] /Volumes/psiqo/_project_/IWS/b4-code/gpte_rr03"; fi
if [ -e "/Volumes/psiqo/_project_/IWS/b4-code/gpte_rr034" ]; then echo "[OK] /Volumes/psiqo/_project_/IWS/b4-code/gpte_rr034"; else echo "[MISSING] /Volumes/psiqo/_project_/IWS/b4-code/gpte_rr034"; fi
if [ -e "/Volumes/psiqo/_project_/IWS/b4-code/gpte_rr036" ]; then echo "[OK] /Volumes/psiqo/_project_/IWS/b4-code/gpte_rr036"; else echo "[MISSING] /Volumes/psiqo/_project_/IWS/b4-code/gpte_rr036"; fi
if [ -e "/Volumes/psiqo/_project_/IWS/b4-code/gpte_rr037" ]; then echo "[OK] /Volumes/psiqo/_project_/IWS/b4-code/gpte_rr037"; else echo "[MISSING] /Volumes/psiqo/_project_/IWS/b4-code/gpte_rr037"; fi
if [ -e "/Volumes/psiqo/_project_/IWS/b4-code/gpte_rr038" ]; then echo "[OK] /Volumes/psiqo/_project_/IWS/b4-code/gpte_rr038"; else echo "[MISSING] /Volumes/psiqo/_project_/IWS/b4-code/gpte_rr038"; fi
if [ -e "/Volumes/psiqo/MetaGPT/workspace/workspace/intelliwealth_solutions" ]; then echo "[OK] /Volumes/psiqo/MetaGPT/workspace/workspace/intelliwealth_solutions"; else echo "[MISSING] /Volumes/psiqo/MetaGPT/workspace/workspace/intelliwealth_solutions"; fi
if [ -e "/Volumes/psiqo/MetaGPT/workspace/intelliwealth_solutions_app" ]; then echo "[OK] /Volumes/psiqo/MetaGPT/workspace/intelliwealth_solutions_app"; else echo "[MISSING] /Volumes/psiqo/MetaGPT/workspace/intelliwealth_solutions_app"; fi
if [ -e "/Volumes/psiqo/MetaGPT/workspace/workspace/intelliwealth_solutions_saas" ]; then echo "[OK] /Volumes/psiqo/MetaGPT/workspace/workspace/intelliwealth_solutions_saas"; else echo "[MISSING] /Volumes/psiqo/MetaGPT/workspace/workspace/intelliwealth_solutions_saas"; fi
if [ -e "/Volumes/psiqo/MetaGPT/workspace/intelliwealth_solutions_upgrade" ]; then echo "[OK] /Volumes/psiqo/MetaGPT/workspace/intelliwealth_solutions_upgrade"; else echo "[MISSING] /Volumes/psiqo/MetaGPT/workspace/intelliwealth_solutions_upgrade"; fi
if [ -e "/Volumes/psiqo/MetaGPT/workspace/workspace/intelliwealth_solutions_upgrade" ]; then echo "[OK] /Volumes/psiqo/MetaGPT/workspace/workspace/intelliwealth_solutions_upgrade"; else echo "[MISSING] /Volumes/psiqo/MetaGPT/workspace/workspace/intelliwealth_solutions_upgrade"; fi
if [ -e "/Volumes/psiqo/__bopper" ]; then echo "[OK] /Volumes/psiqo/__bopper"; else echo "[MISSING] /Volumes/psiqo/__bopper"; fi
if [ -e "/Volumes/psiqo/__bopper/__MACOSX" ]; then echo "[OK] /Volumes/psiqo/__bopper/__MACOSX"; else echo "[MISSING] /Volumes/psiqo/__bopper/__MACOSX"; fi
if [ -e "/Volumes/psiqo/bop_final_repo" ]; then echo "[OK] /Volumes/psiqo/bop_final_repo"; else echo "[MISSING] /Volumes/psiqo/bop_final_repo"; fi
if [ -e "/Volumes/psiqo/inference-0/dify" ]; then echo "[OK] /Volumes/psiqo/inference-0/dify"; else echo "[MISSING] /Volumes/psiqo/inference-0/dify"; fi
if [ -e "/Volumes/psiqo/MetaGPT/workspace/workspace/modernized_codebase" ]; then echo "[OK] /Volumes/psiqo/MetaGPT/workspace/workspace/modernized_codebase"; else echo "[MISSING] /Volumes/psiqo/MetaGPT/workspace/workspace/modernized_codebase"; fi
if [ -e "/Volumes/psiqo/pautobot" ]; then echo "[OK] /Volumes/psiqo/pautobot"; else echo "[MISSING] /Volumes/psiqo/pautobot"; fi
if [ -e "/Volumes/psiqo/erp-app" ]; then echo "[OK] /Volumes/psiqo/erp-app"; else echo "[MISSING] /Volumes/psiqo/erp-app"; fi
if [ -e "/Volumes/psiqo/__bop_final" ]; then echo "[OK] /Volumes/psiqo/__bop_final"; else echo "[MISSING] /Volumes/psiqo/__bop_final"; fi
if [ -e "/Volumes/psiqo/_salvage/20250810_worx/gpt-pilot" ]; then echo "[OK] /Volumes/psiqo/_salvage/20250810_worx/gpt-pilot"; else echo "[MISSING] /Volumes/psiqo/_salvage/20250810_worx/gpt-pilot"; fi
if [ -e "/Volumes/psiqo/gpt-pilot" ]; then echo "[OK] /Volumes/psiqo/gpt-pilot"; else echo "[MISSING] /Volumes/psiqo/gpt-pilot"; fi
if [ -e "/Volumes/psiqo/MetaGPT/workspace/workspace/saas_platform_upgrade" ]; then echo "[OK] /Volumes/psiqo/MetaGPT/workspace/workspace/saas_platform_upgrade"; else echo "[MISSING] /Volumes/psiqo/MetaGPT/workspace/workspace/saas_platform_upgrade"; fi
if [ -e "/Volumes/psiqo/__bopper/payoneer" ]; then echo "[OK] /Volumes/psiqo/__bopper/payoneer"; else echo "[MISSING] /Volumes/psiqo/__bopper/payoneer"; fi
if [ -e "/Volumes/psiqo/MetaGPT/workspace/20240323015113" ]; then echo "[OK] /Volumes/psiqo/MetaGPT/workspace/20240323015113"; else echo "[MISSING] /Volumes/psiqo/MetaGPT/workspace/20240323015113"; fi
if [ -e "/Volumes/psiqo/MetaGPT/workspace/20240323022145" ]; then echo "[OK] /Volumes/psiqo/MetaGPT/workspace/20240323022145"; else echo "[MISSING] /Volumes/psiqo/MetaGPT/workspace/20240323022145"; fi
if [ -e "/Volumes/psiqo/MetaGPT/workspace/20240323022444" ]; then echo "[OK] /Volumes/psiqo/MetaGPT/workspace/20240323022444"; else echo "[MISSING] /Volumes/psiqo/MetaGPT/workspace/20240323022444"; fi
if [ -e "/Volumes/psiqo/MetaGPT/workspace/20240323040729" ]; then echo "[OK] /Volumes/psiqo/MetaGPT/workspace/20240323040729"; else echo "[MISSING] /Volumes/psiqo/MetaGPT/workspace/20240323040729"; fi
if [ -e "/Volumes/psiqo/MetaGPT/workspace/20240414172212" ]; then echo "[OK] /Volumes/psiqo/MetaGPT/workspace/20240414172212"; else echo "[MISSING] /Volumes/psiqo/MetaGPT/workspace/20240414172212"; fi
if [ -e "/Volumes/psiqo/anse" ]; then echo "[OK] /Volumes/psiqo/anse"; else echo "[MISSING] /Volumes/psiqo/anse"; fi
if [ -e "/Volumes/psiqo/MemGPT" ]; then echo "[OK] /Volumes/psiqo/MemGPT"; else echo "[MISSING] /Volumes/psiqo/MemGPT"; fi
if [ -e "/Volumes/psiqo/demolog" ]; then echo "[OK] /Volumes/psiqo/demolog"; else echo "[MISSING] /Volumes/psiqo/demolog"; fi
if [ -e "/Volumes/psiqo/_depolop/depolop" ]; then echo "[OK] /Volumes/psiqo/_depolop/depolop"; else echo "[MISSING] /Volumes/psiqo/_depolop/depolop"; fi
if [ -e "/Volumes/psiqo/_depolop/depolop_22042024" ]; then echo "[OK] /Volumes/psiqo/_depolop/depolop_22042024"; else echo "[MISSING] /Volumes/psiqo/_depolop/depolop_22042024"; fi
if [ -e "/Volumes/psiqo/_salvage/20250810_worx/automata" ]; then echo "[OK] /Volumes/psiqo/_salvage/20250810_worx/automata"; else echo "[MISSING] /Volumes/psiqo/_salvage/20250810_worx/automata"; fi
if [ -e "/Volumes/psiqo/friendlyeats-web" ]; then echo "[OK] /Volumes/psiqo/friendlyeats-web"; else echo "[MISSING] /Volumes/psiqo/friendlyeats-web"; fi
if [ -e "/Volumes/psiqo/MetaGPT" ]; then echo "[OK] /Volumes/psiqo/MetaGPT"; else echo "[MISSING] /Volumes/psiqo/MetaGPT"; fi
if [ -e "/Volumes/psiqo/motorhead" ]; then echo "[OK] /Volumes/psiqo/motorhead"; else echo "[MISSING] /Volumes/psiqo/motorhead"; fi
if [ -e "/Volumes/psiqo/gpt-eng/gpt-engineer" ]; then echo "[OK] /Volumes/psiqo/gpt-eng/gpt-engineer"; else echo "[MISSING] /Volumes/psiqo/gpt-eng/gpt-engineer"; fi
if [ -e "/Volumes/psiqo/ai-money-machine-starter/hydrogen-quickstart" ]; then echo "[OK] /Volumes/psiqo/ai-money-machine-starter/hydrogen-quickstart"; else echo "[MISSING] /Volumes/psiqo/ai-money-machine-starter/hydrogen-quickstart"; fi
if [ -e "/Volumes/psiqo/privateGPT" ]; then echo "[OK] /Volumes/psiqo/privateGPT"; else echo "[MISSING] /Volumes/psiqo/privateGPT"; fi
if [ -e "/Volumes/psiqo/Free-Auto-GPT" ]; then echo "[OK] /Volumes/psiqo/Free-Auto-GPT"; else echo "[MISSING] /Volumes/psiqo/Free-Auto-GPT"; fi
if [ -e "/Volumes/psiqo/crewAI" ]; then echo "[OK] /Volumes/psiqo/crewAI"; else echo "[MISSING] /Volumes/psiqo/crewAI"; fi
if [ -e "/Volumes/psiqo/gpt4all" ]; then echo "[OK] /Volumes/psiqo/gpt4all"; else echo "[MISSING] /Volumes/psiqo/gpt4all"; fi
if [ -e "/Volumes/psiqo/swarm" ]; then echo "[OK] /Volumes/psiqo/swarm"; else echo "[MISSING] /Volumes/psiqo/swarm"; fi
if [ -e "/Volumes/psiqo/Dropbox/Organization/dir/project-management-app" ]; then echo "[OK] /Volumes/psiqo/Dropbox/Organization/dir/project-management-app"; else echo "[MISSING] /Volumes/psiqo/Dropbox/Organization/dir/project-management-app"; fi
if [ -e "/Volumes/psiqo/AgentGPT" ]; then echo "[OK] /Volumes/psiqo/AgentGPT"; else echo "[MISSING] /Volumes/psiqo/AgentGPT"; fi
if [ -e "/Volumes/psiqo/claude-dev" ]; then echo "[OK] /Volumes/psiqo/claude-dev"; else echo "[MISSING] /Volumes/psiqo/claude-dev"; fi
if [ -e "/Volumes/psiqo/awesome-chatgpt" ]; then echo "[OK] /Volumes/psiqo/awesome-chatgpt"; else echo "[MISSING] /Volumes/psiqo/awesome-chatgpt"; fi
if [ -e "/Volumes/psiqo/SuperAGI_0" ]; then echo "[OK] /Volumes/psiqo/SuperAGI_0"; else echo "[MISSING] /Volumes/psiqo/SuperAGI_0"; fi
if [ -e "/Volumes/psiqo/AutoGPT.js" ]; then echo "[OK] /Volumes/psiqo/AutoGPT.js"; else echo "[MISSING] /Volumes/psiqo/AutoGPT.js"; fi
if [ -e "/Volumes/psiqo/_project_/private-gpt" ]; then echo "[OK] /Volumes/psiqo/_project_/private-gpt"; else echo "[MISSING] /Volumes/psiqo/_project_/private-gpt"; fi
if [ -e "/Volumes/psiqo/private-gpt" ]; then echo "[OK] /Volumes/psiqo/private-gpt"; else echo "[MISSING] /Volumes/psiqo/private-gpt"; fi
if [ -e "/Volumes/psiqo/apache-maven-3.9/maven-toolchains-plugin" ]; then echo "[OK] /Volumes/psiqo/apache-maven-3.9/maven-toolchains-plugin"; else echo "[MISSING] /Volumes/psiqo/apache-maven-3.9/maven-toolchains-plugin"; fi
if [ -e "/Volumes/psiqo/maven-toolchains-plugin" ]; then echo "[OK] /Volumes/psiqo/maven-toolchains-plugin"; else echo "[MISSING] /Volumes/psiqo/maven-toolchains-plugin"; fi
if [ -e "/Volumes/psiqo/react-horizon-ui-chakra" ]; then echo "[OK] /Volumes/psiqo/react-horizon-ui-chakra"; else echo "[MISSING] /Volumes/psiqo/react-horizon-ui-chakra"; fi
if [ -e "/Volumes/psiqo/8a6578a2-4707-4e80-aed7-ebefc8bce13b" ]; then echo "[OK] /Volumes/psiqo/8a6578a2-4707-4e80-aed7-ebefc8bce13b"; else echo "[MISSING] /Volumes/psiqo/8a6578a2-4707-4e80-aed7-ebefc8bce13b"; fi
if [ -e "/Volumes/psiqo/astro" ]; then echo "[OK] /Volumes/psiqo/astro"; else echo "[MISSING] /Volumes/psiqo/astro"; fi
if [ -e "/Volumes/psiqo/Desktop/discoveries/autopack/autopack" ]; then echo "[OK] /Volumes/psiqo/Desktop/discoveries/autopack/autopack"; else echo "[MISSING] /Volumes/psiqo/Desktop/discoveries/autopack/autopack"; fi
if [ -e "/Volumes/psiqo/serverless-patterns" ]; then echo "[OK] /Volumes/psiqo/serverless-patterns"; else echo "[MISSING] /Volumes/psiqo/serverless-patterns"; fi
if [ -e "/Volumes/psiqo/microagents" ]; then echo "[OK] /Volumes/psiqo/microagents"; else echo "[MISSING] /Volumes/psiqo/microagents"; fi
if [ -e "/Volumes/psiqo/supercharger" ]; then echo "[OK] /Volumes/psiqo/supercharger"; else echo "[MISSING] /Volumes/psiqo/supercharger"; fi
if [ -e "/Volumes/psiqo/_salvage/20250810_worx/crewAI" ]; then echo "[OK] /Volumes/psiqo/_salvage/20250810_worx/crewAI"; else echo "[MISSING] /Volumes/psiqo/_salvage/20250810_worx/crewAI"; fi
if [ -e "/Volumes/psiqo/forge/AgentForge" ]; then echo "[OK] /Volumes/psiqo/forge/AgentForge"; else echo "[MISSING] /Volumes/psiqo/forge/AgentForge"; fi
if [ -e "/Volumes/psiqo/langchain-experiments" ]; then echo "[OK] /Volumes/psiqo/langchain-experiments"; else echo "[MISSING] /Volumes/psiqo/langchain-experiments"; fi
if [ -e "/Volumes/psiqo/Vid2Persona" ]; then echo "[OK] /Volumes/psiqo/Vid2Persona"; else echo "[MISSING] /Volumes/psiqo/Vid2Persona"; fi
if [ -e "/Volumes/psiqo/cookiecutter-data-science" ]; then echo "[OK] /Volumes/psiqo/cookiecutter-data-science"; else echo "[MISSING] /Volumes/psiqo/cookiecutter-data-science"; fi
if [ -e "/Volumes/psiqo/python-libmagic" ]; then echo "[OK] /Volumes/psiqo/python-libmagic"; else echo "[MISSING] /Volumes/psiqo/python-libmagic"; fi
if [ -e "/Volumes/psiqo/chromedriver" ]; then echo "[OK] /Volumes/psiqo/chromedriver"; else echo "[MISSING] /Volumes/psiqo/chromedriver"; fi
if [ -e "/Volumes/psiqo/electron" ]; then echo "[OK] /Volumes/psiqo/electron"; else echo "[MISSING] /Volumes/psiqo/electron"; fi
if [ -e "/Volumes/psiqo/fantasy-talking" ]; then echo "[OK] /Volumes/psiqo/fantasy-talking"; else echo "[MISSING] /Volumes/psiqo/fantasy-talking"; fi
if [ -e "/Volumes/psiqo/llama.cpp" ]; then echo "[OK] /Volumes/psiqo/llama.cpp"; else echo "[MISSING] /Volumes/psiqo/llama.cpp"; fi
if [ -e "/Volumes/psiqo/muld" ]; then echo "[OK] /Volumes/psiqo/muld"; else echo "[MISSING] /Volumes/psiqo/muld"; fi
if [ -e "/Volumes/psiqo/cookbook" ]; then echo "[OK] /Volumes/psiqo/cookbook"; else echo "[MISSING] /Volumes/psiqo/cookbook"; fi
if [ -e "/Volumes/psiqo/Hexabot" ]; then echo "[OK] /Volumes/psiqo/Hexabot"; else echo "[MISSING] /Volumes/psiqo/Hexabot"; fi
if [ -e "/Volumes/psiqo/_TotalCode/Superagent" ]; then echo "[OK] /Volumes/psiqo/_TotalCode/Superagent"; else echo "[MISSING] /Volumes/psiqo/_TotalCode/Superagent"; fi
if [ -e "/Volumes/psiqo/superagent" ]; then echo "[OK] /Volumes/psiqo/superagent"; else echo "[MISSING] /Volumes/psiqo/superagent"; fi
if [ -e "/Volumes/psiqo/llama_index" ]; then echo "[OK] /Volumes/psiqo/llama_index"; else echo "[MISSING] /Volumes/psiqo/llama_index"; fi
if [ -e "/Volumes/psiqo/karma" ]; then echo "[OK] /Volumes/psiqo/karma"; else echo "[MISSING] /Volumes/psiqo/karma"; fi
if [ -e "/Volumes/psiqo/langchain" ]; then echo "[OK] /Volumes/psiqo/langchain"; else echo "[MISSING] /Volumes/psiqo/langchain"; fi
if [ -e "/Volumes/psiqo/langgraph" ]; then echo "[OK] /Volumes/psiqo/langgraph"; else echo "[MISSING] /Volumes/psiqo/langgraph"; fi
if [ -e "/Volumes/psiqo/webapp-text-generator" ]; then echo "[OK] /Volumes/psiqo/webapp-text-generator"; else echo "[MISSING] /Volumes/psiqo/webapp-text-generator"; fi
if [ -e "/Volumes/psiqo/autogen" ]; then echo "[OK] /Volumes/psiqo/autogen"; else echo "[MISSING] /Volumes/psiqo/autogen"; fi
if [ -e "/Volumes/psiqo/jarvis" ]; then echo "[OK] /Volumes/psiqo/jarvis"; else echo "[MISSING] /Volumes/psiqo/jarvis"; fi
if [ -e "/Volumes/psiqo/raftscope" ]; then echo "[OK] /Volumes/psiqo/raftscope"; else echo "[MISSING] /Volumes/psiqo/raftscope"; fi
if [ -e "/Volumes/psiqo/text-generation-webui" ]; then echo "[OK] /Volumes/psiqo/text-generation-webui"; else echo "[MISSING] /Volumes/psiqo/text-generation-webui"; fi
if [ -e "/Volumes/psiqo/SWELancer-Benchmark" ]; then echo "[OK] /Volumes/psiqo/SWELancer-Benchmark"; else echo "[MISSING] /Volumes/psiqo/SWELancer-Benchmark"; fi
if [ -e "/Volumes/psiqo/example-typescript" ]; then echo "[OK] /Volumes/psiqo/example-typescript"; else echo "[MISSING] /Volumes/psiqo/example-typescript"; fi
if [ -e "/Volumes/psiqo/prefect" ]; then echo "[OK] /Volumes/psiqo/prefect"; else echo "[MISSING] /Volumes/psiqo/prefect"; fi
if [ -e "/Volumes/psiqo/SWE-agent" ]; then echo "[OK] /Volumes/psiqo/SWE-agent"; else echo "[MISSING] /Volumes/psiqo/SWE-agent"; fi
if [ -e "/Volumes/psiqo/rasa" ]; then echo "[OK] /Volumes/psiqo/rasa"; else echo "[MISSING] /Volumes/psiqo/rasa"; fi
if [ -e "/Volumes/psiqo/LlamaIndexTS" ]; then echo "[OK] /Volumes/psiqo/LlamaIndexTS"; else echo "[MISSING] /Volumes/psiqo/LlamaIndexTS"; fi
if [ -e "/Volumes/psiqo/gorilla" ]; then echo "[OK] /Volumes/psiqo/gorilla"; else echo "[MISSING] /Volumes/psiqo/gorilla"; fi
if [ -e "/Volumes/psiqo/kdmc/app.env/Auto-GPT" ]; then echo "[OK] /Volumes/psiqo/kdmc/app.env/Auto-GPT"; else echo "[MISSING] /Volumes/psiqo/kdmc/app.env/Auto-GPT"; fi
if [ -e "/Volumes/psiqo/Copy-URL" ]; then echo "[OK] /Volumes/psiqo/Copy-URL"; else echo "[MISSING] /Volumes/psiqo/Copy-URL"; fi
if [ -e "/Volumes/psiqo/text-generation-webui/extensions/webui_tavernai_charas" ]; then echo "[OK] /Volumes/psiqo/text-generation-webui/extensions/webui_tavernai_charas"; else echo "[MISSING] /Volumes/psiqo/text-generation-webui/extensions/webui_tavernai_charas"; fi
if [ -e "/Volumes/psiqo/headlessui" ]; then echo "[OK] /Volumes/psiqo/headlessui"; else echo "[MISSING] /Volumes/psiqo/headlessui"; fi
if [ -e "/Volumes/psiqo/tensorflow" ]; then echo "[OK] /Volumes/psiqo/tensorflow"; else echo "[MISSING] /Volumes/psiqo/tensorflow"; fi
if [ -e "/Volumes/psiqo/terraform-docs-samples" ]; then echo "[OK] /Volumes/psiqo/terraform-docs-samples"; else echo "[MISSING] /Volumes/psiqo/terraform-docs-samples"; fi
if [ -e "/Volumes/psiqo/SuperAGI_01" ]; then echo "[OK] /Volumes/psiqo/SuperAGI_01"; else echo "[MISSING] /Volumes/psiqo/SuperAGI_01"; fi
if [ -e "/Volumes/psiqo/text-generation-webui-stable_diffusion" ]; then echo "[OK] /Volumes/psiqo/text-generation-webui-stable_diffusion"; else echo "[MISSING] /Volumes/psiqo/text-generation-webui-stable_diffusion"; fi
if [ -e "/Volumes/psiqo/text-generation-webui/extensions/stable_diffusion" ]; then echo "[OK] /Volumes/psiqo/text-generation-webui/extensions/stable_diffusion"; else echo "[MISSING] /Volumes/psiqo/text-generation-webui/extensions/stable_diffusion"; fi
if [ -e "/Volumes/psiqo/text-generation-webui/extensions/text-generation-webui-stable_diffusion" ]; then echo "[OK] /Volumes/psiqo/text-generation-webui/extensions/text-generation-webui-stable_diffusion"; else echo "[MISSING] /Volumes/psiqo/text-generation-webui/extensions/text-generation-webui-stable_diffusion"; fi
if [ -e "/Volumes/psiqo/exllamav2" ]; then echo "[OK] /Volumes/psiqo/exllamav2"; else echo "[MISSING] /Volumes/psiqo/exllamav2"; fi
if [ -e "/Volumes/psiqo/exui" ]; then echo "[OK] /Volumes/psiqo/exui"; else echo "[MISSING] /Volumes/psiqo/exui"; fi
if [ -e "/Volumes/psiqo/unstructured" ]; then echo "[OK] /Volumes/psiqo/unstructured"; else echo "[MISSING] /Volumes/psiqo/unstructured"; fi
if [ -e "/Volumes/psiqo/weaviate" ]; then echo "[OK] /Volumes/psiqo/weaviate"; else echo "[MISSING] /Volumes/psiqo/weaviate"; fi
if [ -e "/Volumes/psiqo/inference" ]; then echo "[OK] /Volumes/psiqo/inference"; else echo "[MISSING] /Volumes/psiqo/inference"; fi
if [ -e "/Volumes/psiqo/_TotalCode/gpt-researcher" ]; then echo "[OK] /Volumes/psiqo/_TotalCode/gpt-researcher"; else echo "[MISSING] /Volumes/psiqo/_TotalCode/gpt-researcher"; fi
if [ -e "/Volumes/psiqo/Desktop/discoveries/autopack/autopack/autopack.wiki" ]; then echo "[OK] /Volumes/psiqo/Desktop/discoveries/autopack/autopack/autopack.wiki"; else echo "[MISSING] /Volumes/psiqo/Desktop/discoveries/autopack/autopack/autopack.wiki"; fi
if [ -e "/Volumes/psiqo/beebot" ]; then echo "[OK] /Volumes/psiqo/beebot"; else echo "[MISSING] /Volumes/psiqo/beebot"; fi
if [ -e "/Volumes/psiqo/beebot-old" ]; then echo "[OK] /Volumes/psiqo/beebot-old"; else echo "[MISSING] /Volumes/psiqo/beebot-old"; fi
if [ -e "/Volumes/psiqo/Desktop/discoveries/autopack/autopack/official" ]; then echo "[OK] /Volumes/psiqo/Desktop/discoveries/autopack/autopack/official"; else echo "[MISSING] /Volumes/psiqo/Desktop/discoveries/autopack/autopack/official"; fi
if [ -e "/Volumes/psiqo/official" ]; then echo "[OK] /Volumes/psiqo/official"; else echo "[MISSING] /Volumes/psiqo/official"; fi
if [ -e "/Volumes/psiqo/GPT-agents" ]; then echo "[OK] /Volumes/psiqo/GPT-agents"; else echo "[MISSING] /Volumes/psiqo/GPT-agents"; fi
if [ -e "/Volumes/psiqo/wolverine" ]; then echo "[OK] /Volumes/psiqo/wolverine"; else echo "[MISSING] /Volumes/psiqo/wolverine"; fi
if [ -e "/Volumes/psiqo/raftscope/bootstrap-contextmenu" ]; then echo "[OK] /Volumes/psiqo/raftscope/bootstrap-contextmenu"; else echo "[MISSING] /Volumes/psiqo/raftscope/bootstrap-contextmenu"; fi
if [ -e "/Volumes/psiqo/raftscope/bootstrap-slider" ]; then echo "[OK] /Volumes/psiqo/raftscope/bootstrap-slider"; else echo "[MISSING] /Volumes/psiqo/raftscope/bootstrap-slider"; fi
if [ -e "/Volumes/psiqo/gpt-crawler" ]; then echo "[OK] /Volumes/psiqo/gpt-crawler"; else echo "[MISSING] /Volumes/psiqo/gpt-crawler"; fi
if [ -e "/Volumes/psiqo/ply" ]; then echo "[OK] /Volumes/psiqo/ply"; else echo "[MISSING] /Volumes/psiqo/ply"; fi
if [ -e "/Volumes/psiqo/awesome-chatgpt-store" ]; then echo "[OK] /Volumes/psiqo/awesome-chatgpt-store"; else echo "[MISSING] /Volumes/psiqo/awesome-chatgpt-store"; fi
if [ -e "/Volumes/psiqo/fiddle" ]; then echo "[OK] /Volumes/psiqo/fiddle"; else echo "[MISSING] /Volumes/psiqo/fiddle"; fi
if [ -e "/Volumes/psiqo/text-generation-webui/extensions/dynamic_context" ]; then echo "[OK] /Volumes/psiqo/text-generation-webui/extensions/dynamic_context"; else echo "[MISSING] /Volumes/psiqo/text-generation-webui/extensions/dynamic_context"; fi
if [ -e "/Volumes/psiqo/text-generation-webui/extensions/alltalk_tts" ]; then echo "[OK] /Volumes/psiqo/text-generation-webui/extensions/alltalk_tts"; else echo "[MISSING] /Volumes/psiqo/text-generation-webui/extensions/alltalk_tts"; fi
if [ -e "/Volumes/psiqo/autopack-demo" ]; then echo "[OK] /Volumes/psiqo/autopack-demo"; else echo "[MISSING] /Volumes/psiqo/autopack-demo"; fi
if [ -e "/Volumes/psiqo/Desktop/discoveries/autopack/autopack-demo" ]; then echo "[OK] /Volumes/psiqo/Desktop/discoveries/autopack/autopack-demo"; else echo "[MISSING] /Volumes/psiqo/Desktop/discoveries/autopack/autopack-demo"; fi
if [ -e "/Volumes/psiqo/Desktop/discoveries/autopack/autopack/autopack-demo" ]; then echo "[OK] /Volumes/psiqo/Desktop/discoveries/autopack/autopack/autopack-demo"; else echo "[MISSING] /Volumes/psiqo/Desktop/discoveries/autopack/autopack/autopack-demo"; fi
if [ -e "/Volumes/psiqo/Desktop/discoveries/autopack/autopack/autopack-demo/demo/autopack-demo" ]; then echo "[OK] /Volumes/psiqo/Desktop/discoveries/autopack/autopack/autopack-demo/demo/autopack-demo"; else echo "[MISSING] /Volumes/psiqo/Desktop/discoveries/autopack/autopack/autopack-demo/demo/autopack-demo"; fi
if [ -e "/Volumes/psiqo/text-generation-webui/extensions/FPreloader" ]; then echo "[OK] /Volumes/psiqo/text-generation-webui/extensions/FPreloader"; else echo "[MISSING] /Volumes/psiqo/text-generation-webui/extensions/FPreloader"; fi
if [ -e "/Volumes/psiqo/text-generation-webui/extensions/Twinbook" ]; then echo "[OK] /Volumes/psiqo/text-generation-webui/extensions/Twinbook"; else echo "[MISSING] /Volumes/psiqo/text-generation-webui/extensions/Twinbook"; fi
if [ -e "/Volumes/psiqo/text-generation-webui/extensions/VirtualLora" ]; then echo "[OK] /Volumes/psiqo/text-generation-webui/extensions/VirtualLora"; else echo "[MISSING] /Volumes/psiqo/text-generation-webui/extensions/VirtualLora"; fi
if [ -e "/Volumes/psiqo/MetaGPT_0" ]; then echo "[OK] /Volumes/psiqo/MetaGPT_0"; else echo "[MISSING] /Volumes/psiqo/MetaGPT_0"; fi
if [ -e "/Volumes/psiqo/llama.cpp_0" ]; then echo "[OK] /Volumes/psiqo/llama.cpp_0"; else echo "[MISSING] /Volumes/psiqo/llama.cpp_0"; fi
if [ -e "/Volumes/psiqo/magic-modules" ]; then echo "[OK] /Volumes/psiqo/magic-modules"; else echo "[MISSING] /Volumes/psiqo/magic-modules"; fi
if [ -e "/Volumes/psiqo/text-generation-webui/extensions/sd_api_pictures_tag_injection" ]; then echo "[OK] /Volumes/psiqo/text-generation-webui/extensions/sd_api_pictures_tag_injection"; else echo "[MISSING] /Volumes/psiqo/text-generation-webui/extensions/sd_api_pictures_tag_injection"; fi
if [ -e "/Volumes/psiqo/text-generation-webui/extensions/oobabooga-jsonformer-plugin" ]; then echo "[OK] /Volumes/psiqo/text-generation-webui/extensions/oobabooga-jsonformer-plugin"; else echo "[MISSING] /Volumes/psiqo/text-generation-webui/extensions/oobabooga-jsonformer-plugin"; fi
if [ -e "/Volumes/psiqo/text-generation-webui/extensions/AutoSave" ]; then echo "[OK] /Volumes/psiqo/text-generation-webui/extensions/AutoSave"; else echo "[MISSING] /Volumes/psiqo/text-generation-webui/extensions/AutoSave"; fi
if [ -e "/Volumes/psiqo/text-generation-webui/extensions/SpeakLocal" ]; then echo "[OK] /Volumes/psiqo/text-generation-webui/extensions/SpeakLocal"; else echo "[MISSING] /Volumes/psiqo/text-generation-webui/extensions/SpeakLocal"; fi
if [ -e "/Volumes/psiqo/privateGPT-0" ]; then echo "[OK] /Volumes/psiqo/privateGPT-0"; else echo "[MISSING] /Volumes/psiqo/privateGPT-0"; fi
if [ -e "/Volumes/psiqo/Free-personal-AI-Assistant-with-plugin" ]; then echo "[OK] /Volumes/psiqo/Free-personal-AI-Assistant-with-plugin"; else echo "[MISSING] /Volumes/psiqo/Free-personal-AI-Assistant-with-plugin"; fi
if [ -e "/Volumes/psiqo/text-generation-webui/extensions/api_advanced" ]; then echo "[OK] /Volumes/psiqo/text-generation-webui/extensions/api_advanced"; else echo "[MISSING] /Volumes/psiqo/text-generation-webui/extensions/api_advanced"; fi
if [ -e "/Volumes/psiqo/text-generation-webui/extensions/multi_translate" ]; then echo "[OK] /Volumes/psiqo/text-generation-webui/extensions/multi_translate"; else echo "[MISSING] /Volumes/psiqo/text-generation-webui/extensions/multi_translate"; fi
if [ -e "/Volumes/psiqo/text-generation-webui/extensions/long_term_memory_with_qdrant" ]; then echo "[OK] /Volumes/psiqo/text-generation-webui/extensions/long_term_memory_with_qdrant"; else echo "[MISSING] /Volumes/psiqo/text-generation-webui/extensions/long_term_memory_with_qdrant"; fi
if [ -e "/Volumes/psiqo/FastChat" ]; then echo "[OK] /Volumes/psiqo/FastChat"; else echo "[MISSING] /Volumes/psiqo/FastChat"; fi
if [ -e "/Volumes/psiqo/lmstudio.js/configs" ]; then echo "[OK] /Volumes/psiqo/lmstudio.js/configs"; else echo "[MISSING] /Volumes/psiqo/lmstudio.js/configs"; fi
if [ -e "/Volumes/psiqo/lmstudio.js" ]; then echo "[OK] /Volumes/psiqo/lmstudio.js"; else echo "[MISSING] /Volumes/psiqo/lmstudio.js"; fi
if [ -e "/Volumes/psiqo/lmstudio.js/model-catalog" ]; then echo "[OK] /Volumes/psiqo/lmstudio.js/model-catalog"; else echo "[MISSING] /Volumes/psiqo/lmstudio.js/model-catalog"; fi
if [ -e "/Volumes/psiqo/text-generation-webui/extensions/LLM_Web_search" ]; then echo "[OK] /Volumes/psiqo/text-generation-webui/extensions/LLM_Web_search"; else echo "[MISSING] /Volumes/psiqo/text-generation-webui/extensions/LLM_Web_search"; fi
if [ -e "/Volumes/psiqo/OpenManus" ]; then echo "[OK] /Volumes/psiqo/OpenManus"; else echo "[MISSING] /Volumes/psiqo/OpenManus"; fi
if [ -e "/Volumes/psiqo/experts" ]; then echo "[OK] /Volumes/psiqo/experts"; else echo "[MISSING] /Volumes/psiqo/experts"; fi
if [ -e "/Volumes/psiqo/inference-0/llama-cpp-python" ]; then echo "[OK] /Volumes/psiqo/inference-0/llama-cpp-python"; else echo "[MISSING] /Volumes/psiqo/inference-0/llama-cpp-python"; fi
if [ -e "/Volumes/psiqo/pgvector" ]; then echo "[OK] /Volumes/psiqo/pgvector"; else echo "[MISSING] /Volumes/psiqo/pgvector"; fi
if [ -e "/Volumes/psiqo/pyenv" ]; then echo "[OK] /Volumes/psiqo/pyenv"; else echo "[MISSING] /Volumes/psiqo/pyenv"; fi
if [ -e "/Volumes/psiqo/pyenv/plugins/pyenv-virtualenv" ]; then echo "[OK] /Volumes/psiqo/pyenv/plugins/pyenv-virtualenv"; else echo "[MISSING] /Volumes/psiqo/pyenv/plugins/pyenv-virtualenv"; fi
if [ -e "/Volumes/psiqo/pyenv/plugins/pyenv-virtualenvwrapper" ]; then echo "[OK] /Volumes/psiqo/pyenv/plugins/pyenv-virtualenvwrapper"; else echo "[MISSING] /Volumes/psiqo/pyenv/plugins/pyenv-virtualenvwrapper"; fi
if [ -e "/Volumes/psiqo/pypy" ]; then echo "[OK] /Volumes/psiqo/pypy"; else echo "[MISSING] /Volumes/psiqo/pypy"; fi
if [ -e "/Volumes/psiqo/text-generation-webui/extensions/LucidWebSearch" ]; then echo "[OK] /Volumes/psiqo/text-generation-webui/extensions/LucidWebSearch"; else echo "[MISSING] /Volumes/psiqo/text-generation-webui/extensions/LucidWebSearch"; fi
if [ -e "/Volumes/psiqo/text-generation-webui/extensions/text-generation-webui-barktts" ]; then echo "[OK] /Volumes/psiqo/text-generation-webui/extensions/text-generation-webui-barktts"; else echo "[MISSING] /Volumes/psiqo/text-generation-webui/extensions/text-generation-webui-barktts"; fi
if [ -e "/Volumes/psiqo/gpt-code-ui" ]; then echo "[OK] /Volumes/psiqo/gpt-code-ui"; else echo "[MISSING] /Volumes/psiqo/gpt-code-ui"; fi
if [ -e "/Volumes/psiqo/claude-dev copy" ]; then echo "[OK] /Volumes/psiqo/claude-dev copy"; else echo "[MISSING] /Volumes/psiqo/claude-dev copy"; fi
if [ -e "/Volumes/psiqo/text-generation-webui/extensions/complex_memory" ]; then echo "[OK] /Volumes/psiqo/text-generation-webui/extensions/complex_memory"; else echo "[MISSING] /Volumes/psiqo/text-generation-webui/extensions/complex_memory"; fi
if [ -e "/Volumes/psiqo/text-generation-webui/extensions/more_translators" ]; then echo "[OK] /Volumes/psiqo/text-generation-webui/extensions/more_translators"; else echo "[MISSING] /Volumes/psiqo/text-generation-webui/extensions/more_translators"; fi
if [ -e "/Volumes/psiqo/text-generation-webui/extensions/google_translate_plus" ]; then echo "[OK] /Volumes/psiqo/text-generation-webui/extensions/google_translate_plus"; else echo "[MISSING] /Volumes/psiqo/text-generation-webui/extensions/google_translate_plus"; fi
if [ -e "/Volumes/psiqo/text-generation-webui/extensions/long_term_memory" ]; then echo "[OK] /Volumes/psiqo/text-generation-webui/extensions/long_term_memory"; else echo "[MISSING] /Volumes/psiqo/text-generation-webui/extensions/long_term_memory"; fi
if [ -e "/Volumes/psiqo/inference-0" ]; then echo "[OK] /Volumes/psiqo/inference-0"; else echo "[MISSING] /Volumes/psiqo/inference-0"; fi
if [ -e "/Volumes/psiqo/libyaml" ]; then echo "[OK] /Volumes/psiqo/libyaml"; else echo "[MISSING] /Volumes/psiqo/libyaml"; fi