
timeout: "1800s"
substitutions:
  _SERVICE_NAME: "autonomax-api"
  _REGION: "us-central1"
  _IMAGE: "gcr.io/${PROJECT_ID}/autonomax-api"
steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "${_IMAGE}", "."]
  - name: gcr.io/cloud-builders/docker
    args: ["push", "${_IMAGE}"]
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -lc
      - |
        gcloud run deploy ${_SERVICE_NAME} \
          --image ${_IMAGE} \
          --platform managed \
          --region ${_REGION} \
          --allow-unauthenticated \
          --set-env-vars ENV=prod \
          --set-secrets OPENAI_API_KEY=OPENAI_API_KEY:latest,SHOPIFY_ADMIN_TOKEN=SHOPIFY_ADMIN_TOKEN:latest,SHOPIFY_API_SECRET=SHOPIFY_API_SECRET:latest,SLACK_WEBHOOK_URL=SLACK_WEBHOOK_URL:latest,GA_CREDENTIALS_JSON=GA_CREDENTIALS_JSON:latest \
          --min-instances=0 --max-instances=2 --concurrency=80 --memory=512Mi --timeout=300 --cpu-throttling \
          --quiet
images: ["${_IMAGE}"]
